id: P001745
initial_creation_type: ocr
source_metadata:
  id: bdr:W1GS44028
  title: བོད་ཀྱི་རིག་གནས་ལོ་རྒྱུས་དཔྱད་གཞིའི་རྒྱུ་ཆ་བདམས་བསྒྲིགས་༔ ༡༠ ༼༡༩༽
  author: ''
  volumes:
    74191b7cea77453a8a0d5d7b63e9cfc8:
      image_group_id: I5819
      title: ''
      volume_number: 1
      total_pages: 277
      base_file: v001.txt
